services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: de_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: de_user
      CLICKHOUSE_PASSWORD: de_password
      CLICKHOUSE_DB: default
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
